name: apod
description: "Astronomy Picture of the Day"

publish_to: 'none' 

version: 1.0.0+1

environment:
  flutter: 3.24.4
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  dio: ^5.7.0
  html: ^0.15.5
  url_launcher: ^6.3.1

  intl: ^0.20.0

  flutter_modular: ^6.3.4

  mobx: ^2.4.0
  flutter_mobx: ^2.2.1+1
  mobx_codegen: ^2.6.2

  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
